Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
   config.vm.network "public_network"
   config.vm.define :SecurityLab
   config.vm.define "MyServer" do |myserver|
	myserver.vm.box = "bento/ubuntu-18.04"
	myserver.vm.hostname = "MyServer"
	myserver.vm.network :public_network
	myserver.vm.provision :shell, inline: <<-SHELL
		apt-get update
		apt-get install -y avahi-daemon libnss-mdns
		apt-get install nmap -y
		ncat -l -k 0.0.0.0 4444 >> /home/vagrant/log.log &
		apt-get install apache2 php -y
		
		echo "vagrant" | sudo -S sh -c "echo '<h1>MegaCorp Static Site</h1><p>Secure this box and make sure no silly intern left any security holes or unuse programs</p>' > /var/www/html/index.html"
		php -S 0.0.0.0:8000 &
		echo 'sleep 30
		echo "vagrant" | sudo -kS sh -c "echo Port 2000 >> /etc/ssh/sshd_config"             echo "vagrant" | sudo -kS sh -c "echo Port 22 >> /etc/ssh/sshd_config"               echo "vagrant" | sudo -kS sh -c "echo Port 2001 >> /etc/ssh/sshd_config"             echo "vagrant" | sudo -S systemctl restart sshd' > /home/vagrant/.payload.sh
		chmod u+x /home/vagrant/.payload.sh
		/home/vagrant/.payload.sh &
		echo 'sleep 300
		echo "vagrant" | sudo -kS apt-get install rabbitmq-server -y
		ncat -l -k -u 0.0.0.0 1337 >> /home/vagrant/anotherone.log &
		' > /home/vagrant/.payload2.sh
		chmod u+x /home/vagrant/.payload2.sh
		/home/vagrant/.payload2.sh &
		
	SHELL
  end


   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "512"
   end
end
